version: '2'

services:
  pg:
    image: postgres:9.4
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"


  web:
    build: web
    volumes:
      - ./web:/app
    ports:
      - "3000:80"
    env_file:
      - ./web/.env.dev
    links:
      - pg
      - redis
      

